import type { Metadata } from "next";
import "./globals.css";
import Mainfooter from "./components/Mainfooter";

export const metadata: Metadata = {
  title: "Virtual Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Mainfooter />
    </html>
  );
}
