import type { Metadata } from "next";
import "./globals.css";
// import Mainfooter from "./components/Mainfooter";
// import Mainheader from "./components/Mainheader";

export const metadata: Metadata = {
  title: "Virtual Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Mainheader /> */}
        {children}
        {/* <Mainfooter /> */}
      </body>
    </html>
  );
}
